### ISSUE TITLE
Retrieve username and image from the local storage and display in the game page

### ISSUE THREAD

**Issue by Divyapriyababu** [danielstewart914/cards-for-jokes#36]

**Comment by danielstewart914** [comment]
Just an FYI in case you hadn't seen the variables. No need to make you duplicate work that's already been done.

username and theme index are already retrieved from local storage at the beginning of main.js and stored in the variables userName and themeIndex ( lines 6 and 7 ). If you want to display them on the gamepage you just need to call those variables in gamepage.js. The themeIndex is the users selected index of the theme array on line 9 of main.js that contains links to all the images for the themes.
